### ISSUE TITLE
Remove `--passWithNoTests`

### ISSUE THREAD

**Issue by jakebax** [jakebax/new-jac-city#1]
As soon as we begin adding tests to the repo, we should remove the `--passWithNoTests` flag on the `test` script in `package.json`:

```json
    "test:local": "jest --passWithNoTests",
```

**Comment by nathanbowang** [comment]
I will remove the `--passWithNoTests` option once adds a test to the project. 
Is it necessary to add a `--watch` option?

**Comment by jakebax** [comment]
No, if you want to run it in watch mode, you just do `pnpm test:local --watch`.

**Comment by nathanbowang** [comment]
OK, I see.
